### ISSUE TITLE
Feature: Make Icons in Headings possible

### ISSUE THREAD

**Issue by fwolfst** [giterlizzi/dokuwiki-plugin-icons#24]
If I enter an icon in a heading like

    ==  {{mdi>axis-x-y-arrow-lock}} Infos ==

the icon itself will not be rendered. Would be cool to have the icons embeddable in headings.

**Comment by giterlizzi** [comment]
Hi @fwolfst,
the standard DokuWiki syntax don't permit other syntax inside headings... but you can use this Icons plugin workaround:

```
{{mdi>axis-x-y-arrow-lock?align=left}} ==  Infos ==
```

Joseph
